name: Feature
description: New feature request
labels: [feature]
body:
  - type: input
    id: goal
    attributes: { label: Outcome, placeholder: "What the user gets" }
  - type: textarea
    id: scope
    attributes: { label: Scope, description: "In / Out" }
  - type: checkboxes
    id: done
    attributes:
      label: Definition of Done
      options:
        - label: Tests added
        - label: a11y checked
        - label: Docs updated
